version: "3.9"

services:
  illa-builder:
    container_name: ${CONTAINER_NAME}
    restart: always
    image: "illasoft/illa-builder:${SOFTWARE_VERSION_TAG}"
    environment:
    - GIN_MODE=release
    - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "172.17.0.1:3050:2022"
    volumes:
      - ./data:/var/lib/postgresql/data 
